# Required
version: 2

build:
  os: "ubuntu-20.04"
  apt_packages:
    - libsndfile1
  tools:
    python: "3.10"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
